url: "https://evandejes.us" # the base hostname & protocol for your site, e.g. http://example.com
title: "Evan" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

navigation:
  - title: Home
    url: /
  - title: About
    url: /about.html
